package teste;

public class bmth {

	public static void main(String[] args) {
		
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW=*WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW@*-.......-......-+#WWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWW*..:=WW=.-#WWWW@+.:WW#+..+@WWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWW#-.+WWWWW:.=WWWWWWWW@-.@WWWW*..=WWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWW#-.=WWWWWW+.#WWWWWWWWWWW-.WWWWWW@-.=WWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWW+.*WWWWWWW#.*WWWWWWWWWWWW#.+WWWWWWW#.-WWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWW@-.@WWWWWWWW+.@WWWWWWWWWWWWW:.@WWWWWWWW-.#WWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWW@.-WWWWWWWWWW--WWWWWWWWWWWWWW*.#WWWWWWWWW:.#WWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWW--WWWWWWWWWW@.:WWWWWWWWWWWWWW=.=WWWWWWWWWW:.@WWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWW:.*-..--...:#@.:WW*........+@W=.=@+...--...*--WWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWW=..:@WWWWWWW#-..-:.+WWW-.@WW*.-*...*WWWWWWWW+..*WWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWW-.#WWWWWWWWWWW*..-@WWWW-.@WWWW:..:WWWWWWWWWWW@-.WWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWW#.*WWWWWWWWWWWWW:.#WWWWW-.@WWWW@..WWWWWWWWWWWWW=.*WWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWW#:@WWWWWW@WWWWWW=+WWWWWW-.@WWWWW**WWWWWWWW@WWWWW+=WWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWW=.@WWWWWWWWWWWWW-.@WWWWWWWWWWWWWW=.@WWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWW:.=WWWWWWWWWWWWW-.@WWWWWWWWWWWWWW:.=WWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#-WWWW-.@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW+.=WWW-.@WWWWWWW+*WWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#+WWWW-.@WWWWWW@.-WWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW-.@WWWWWWW*=WWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW-.@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW-.@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW-.@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW-.@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW-.@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW-.@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		System.out.println("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
		
		
		
		
		
		

	}

}
